# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'MakemojiSDKDemo' do
pod "AFNetworking", "2.6.3"
pod 'SDWebImage', "3.7.3"
end

target 'MakemojiSDKDemoTests' do

end

